config:
  credentials: []
  project_repos:
    codebase.helmholtz.cloud/m-team/ai/demo-advanced-api:
      branch: main
      repo: https://codebase.helmholtz.cloud/m-team/ai/demo-advanced-api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/demo-advanced-api git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-pear-capuchin.sh
        container: qc.acc_sleazy-lime-balinese
  QC.Doc:
    repos:
      codebase.helmholtz.cloud/m-team/ai/demo-advanced-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cyan-walrus.sh
        container: qc.doc_paltry-firebrick-sponge
      codebase.helmholtz.cloud/m-team/ai/demo-advanced-api git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lemon-corgi.sh
        container: qc.doc_zippy-cream-clam
  QC.Lic:
    repos:
      codebase.helmholtz.cloud/m-team/ai/demo-advanced-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cerise-grouse.sh
        container: qc.lic_muggy-heliotrope-lobster
  QC.Ver:
    repos:
      codebase.helmholtz.cloud/m-team/ai/demo-advanced-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-blue-ferret.sh
        container: qc.ver_trippy-burgundy-wombat
timeout: 5400
